# Generated by Django 5.2.17 on 2026-08-24 15:57

import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("crm", "0001_initial"),
        ("mediahub", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Collection",
            fields=[
                ("collection_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "code",
                    models.CharField(blank=True, max_length=32, null=True, unique=True),
                ),
                ("name", models.CharField(max_length=120)),
                ("story", models.TextField(blank=True, null=True)),
                ("is_bestseller", models.BooleanField(default=False)),
                ("launched_on", models.DateField(blank=True, null=True)),
            ],
            options={
                "db_table": "collection",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                ("location_id", models.AutoField(primary_key=True, serialize=False)),
                ("code", models.CharField(max_length=32, unique=True)),
                ("name", models.CharField(max_length=120)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("SHOWROOM", "Showroom"),
                            ("GODOWN", "Godown"),
                            ("WORKSHOP", "Workshop"),
                            ("VENDOR", "Vendor"),
                            ("TRANSIT", "Transit"),
                        ],
                        default="SHOWROOM",
                        max_length=16,
                    ),
                ),
                ("city", models.CharField(blank=True, max_length=80, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "location",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="MaterialCategory",
            fields=[
                (
                    "code",
                    models.CharField(max_length=32, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=80, unique=True)),
                ("sort_order", models.IntegerField(default=0)),
                ("is_priceable", models.BooleanField(default=True)),
                ("note", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "material categories",
                "db_table": "material_category",
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="SystemSetting",
            fields=[
                (
                    "key",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("value", models.TextField()),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "system_setting",
            },
        ),
        migrations.CreateModel(
            name="UomConversion",
            fields=[
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("CT", "Carat"),
                            ("GM", "Gram"),
                            ("RATTI", "Ratti"),
                            ("PCS", "Pieces"),
                        ],
                        db_column="unit",
                        max_length=8,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "grams_per_unit",
                    models.DecimalField(decimal_places=6, max_digits=12),
                ),
            ],
            options={
                "db_table": "uom_conversion",
            },
        ),
        migrations.CreateModel(
            name="Vendor",
            fields=[
                ("vendor_id", models.AutoField(primary_key=True, serialize=False)),
                ("code", models.CharField(max_length=32, unique=True)),
                ("name", models.CharField(max_length=120)),
                ("contact", models.CharField(blank=True, max_length=120, null=True)),
                ("city", models.CharField(blank=True, max_length=80, null=True)),
                (
                    "avg_tat_days",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "vendor",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="CatalogueTemplate",
            fields=[
                ("template_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=120)),
                ("layout", models.CharField(default="GRID_2x2", max_length=32)),
                ("show_sale_price", models.BooleanField(default=True)),
                ("show_cost_price", models.BooleanField(default=False)),
                ("show_material_breakup", models.BooleanField(default=False)),
                ("show_dimensions", models.BooleanField(default=True)),
                ("show_gross_weight", models.BooleanField(default=True)),
                ("show_location", models.BooleanField(default=False)),
                ("show_in_stock_flag", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="created_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "catalogue_template",
            },
        ),
        migrations.CreateModel(
            name="Catalogue",
            fields=[
                ("catalogue_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=120)),
                (
                    "generated_for",
                    models.CharField(blank=True, max_length=160, null=True),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("output_url", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "generated_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="generated_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        db_column="template_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="catalogues",
                        to="stock.cataloguetemplate",
                    ),
                ),
            ],
            options={
                "db_table": "catalogue",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                ("category_id", models.AutoField(primary_key=True, serialize=False)),
                ("code", models.CharField(max_length=32, unique=True)),
                ("name", models.CharField(max_length=120)),
                ("code_prefix", models.CharField(blank=True, max_length=8, null=True)),
                ("sort_order", models.IntegerField(default=0)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        db_column="parent_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="stock.category",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "categories",
                "db_table": "category",
                "ordering": ["sort_order", "code"],
            },
        ),
        migrations.CreateModel(
            name="Metal",
            fields=[
                (
                    "code",
                    models.CharField(max_length=32, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=80)),
                (
                    "pure_rate",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0001"))
                        ],
                    ),
                ),
                ("rate_as_on", models.DateTimeField(auto_now_add=True)),
                ("unit", models.CharField(default="GM", max_length=8)),
                ("note", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "metal",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("pure_rate__gt", 0)),
                        name="metal_rate_positive",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Material",
            fields=[
                ("material_id", models.AutoField(primary_key=True, serialize=False)),
                ("item_code", models.CharField(max_length=64, unique=True)),
                ("item_name", models.CharField(max_length=160)),
                ("description", models.TextField(blank=True, null=True)),
                ("size", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "mat_class",
                    models.CharField(
                        choices=[
                            ("METAL", "Metal"),
                            ("DIAMOND", "Diamond"),
                            ("POLKI", "Polki"),
                            ("COLOUR_STONE", "Colour stone"),
                            ("PEARL", "Pearl"),
                            ("FINDING", "Finding"),
                            ("LABOUR", "Labour"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "default_uom",
                    models.CharField(
                        choices=[
                            ("CT", "Carat"),
                            ("GM", "Gram"),
                            ("RATTI", "Ratti"),
                            ("PCS", "Pieces"),
                        ],
                        max_length=8,
                    ),
                ),
                (
                    "purity_factor",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=6, null=True
                    ),
                ),
                ("needs_review", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "category",
                    models.ForeignKey(
                        db_column="category",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="materials",
                        to="stock.materialcategory",
                    ),
                ),
                (
                    "metal",
                    models.ForeignKey(
                        blank=True,
                        db_column="metal",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="materials",
                        to="stock.metal",
                    ),
                ),
            ],
            options={
                "db_table": "material",
                "ordering": ["item_code"],
            },
        ),
        migrations.CreateModel(
            name="MetalPurity",
            fields=[
                (
                    "karat",
                    models.CharField(max_length=16, primary_key=True, serialize=False),
                ),
                ("sale_factor", models.DecimalField(decimal_places=4, max_digits=6)),
                ("true_fineness", models.DecimalField(decimal_places=4, max_digits=6)),
                ("sort_order", models.IntegerField(default=0)),
                (
                    "metal",
                    models.ForeignKey(
                        db_column="metal",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purities",
                        to="stock.metal",
                    ),
                ),
            ],
            options={
                "db_table": "metal_purity",
                "ordering": ["metal_id", "sort_order"],
            },
        ),
        migrations.CreateModel(
            name="Piece",
            fields=[
                ("jewel_code_id", models.AutoField(primary_key=True, serialize=False)),
                ("jewel_code", models.CharField(max_length=64, unique=True)),
                (
                    "sub_category",
                    models.CharField(blank=True, max_length=80, null=True),
                ),
                (
                    "metal_purity",
                    models.CharField(
                        blank=True,
                        help_text="Karat, e.g. 18K or 925.",
                        max_length=16,
                        null=True,
                    ),
                ),
                (
                    "metal_colour",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                ("size_label", models.CharField(blank=True, max_length=32, null=True)),
                (
                    "diamond_quality",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "measured_gross_wt_gm",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                (
                    "length_mm",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "breadth_mm",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "height_mm",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("fg_date", models.DateField(blank=True, null=True)),
                (
                    "stock_type",
                    models.CharField(
                        blank=True, default="FINISH_GOODS", max_length=32, null=True
                    ),
                ),
                (
                    "huid",
                    models.CharField(blank=True, max_length=32, null=True, unique=True),
                ),
                ("hallmarked_on", models.DateField(blank=True, null=True)),
                (
                    "hallmark_centre",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                (
                    "stock_state",
                    models.CharField(
                        choices=[
                            ("NOT_RECEIVED", "Not received"),
                            ("IN_STOCK", "In stock"),
                            ("RESERVED", "Reserved"),
                            ("ON_APPROVAL", "On approval"),
                            ("IN_TRANSIT", "In transit"),
                            ("IN_REPAIR", "In repair"),
                            ("SOLD", "Sold"),
                            ("MELTED", "Melted"),
                            ("LOST", "Lost"),
                        ],
                        default="NOT_RECEIVED",
                        max_length=16,
                    ),
                ),
                ("received_on", models.DateField(blank=True, null=True)),
                ("disposed_on", models.DateField(blank=True, null=True)),
                ("current_bom_version", models.IntegerField(default=1)),
                ("on_website", models.BooleanField(default=False)),
                ("website_url", models.URLField(blank=True, max_length=500, null=True)),
                ("remarks", models.TextField(blank=True, null=True)),
                ("src_system", models.CharField(blank=True, max_length=40, null=True)),
                ("src_ref", models.CharField(blank=True, max_length=80, null=True)),
                (
                    "src_cost_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "src_sale_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "src_tag_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "src_net_wt_gm",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                ("bom_is_summary", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="created_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        db_column="location_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pieces",
                        to="stock.location",
                    ),
                ),
            ],
            options={
                "db_table": "jewel_code",
                "ordering": ["jewel_code"],
            },
        ),
        migrations.CreateModel(
            name="MeltRecord",
            fields=[
                ("melt_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("bom_version_at_melt", models.IntegerField()),
                ("melted_on", models.DateField()),
                ("reason", models.TextField()),
                (
                    "cost_written_off",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "authorised_by",
                    models.ForeignKey(
                        db_column="authorised_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        db_column="location_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="melts",
                        to="stock.location",
                    ),
                ),
                (
                    "piece",
                    models.OneToOneField(
                        db_column="jewel_code_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="melt",
                        to="stock.piece",
                    ),
                ),
            ],
            options={
                "db_table": "melt_record",
            },
        ),
        migrations.CreateModel(
            name="CatalogueItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_order", models.IntegerField(default=0)),
                (
                    "catalogue",
                    models.ForeignKey(
                        db_column="catalogue_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="stock.catalogue",
                    ),
                ),
                (
                    "media",
                    models.ForeignKey(
                        blank=True,
                        db_column="media_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="mediahub.mediaasset",
                    ),
                ),
                (
                    "piece",
                    models.ForeignKey(
                        db_column="jewel_code_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="catalogue_items",
                        to="stock.piece",
                    ),
                ),
            ],
            options={
                "db_table": "catalogue_item",
            },
        ),
        migrations.CreateModel(
            name="BomLine",
            fields=[
                ("line_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("version_no", models.IntegerField()),
                ("line_no", models.IntegerField()),
                ("size_band", models.CharField(blank=True, default="", max_length=64)),
                ("pcs", models.IntegerField(blank=True, null=True)),
                (
                    "qty_value",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "qty_uom",
                    models.CharField(
                        choices=[
                            ("CT", "Carat"),
                            ("GM", "Gram"),
                            ("RATTI", "Ratti"),
                            ("PCS", "Pieces"),
                        ],
                        max_length=8,
                    ),
                ),
                (
                    "basis",
                    models.CharField(
                        choices=[
                            ("BY_QTY", "By quantity"),
                            ("BY_NET_METAL_WT", "By net metal weight"),
                            ("BY_GROSS_WT", "By gross weight"),
                            ("BY_PIECE", "By piece"),
                            ("FLAT", "Flat"),
                        ],
                        default="BY_QTY",
                        max_length=20,
                    ),
                ),
                (
                    "cost_rate",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                (
                    "cost_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "sale_rate",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                (
                    "sale_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "off_chart",
                    models.BooleanField(
                        default=False,
                        help_text="Carries a rate that differs from the chart it was priced against — deliberate, and findable later.",
                    ),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "material",
                    models.ForeignKey(
                        db_column="material_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bom_lines",
                        to="stock.material",
                    ),
                ),
                (
                    "piece",
                    models.ForeignKey(
                        db_column="jewel_code_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bom_lines",
                        to="stock.piece",
                    ),
                ),
            ],
            options={
                "db_table": "jewel_material_line",
                "ordering": ["piece_id", "version_no", "line_no"],
            },
        ),
        migrations.CreateModel(
            name="PieceCertificate",
            fields=[
                ("certificate_id", models.AutoField(primary_key=True, serialize=False)),
                ("company", models.CharField(max_length=80)),
                ("cert_number", models.CharField(max_length=80)),
                ("issued_on", models.DateField(blank=True, null=True)),
                (
                    "piece",
                    models.ForeignKey(
                        db_column="jewel_code_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificates",
                        to="stock.piece",
                    ),
                ),
            ],
            options={
                "db_table": "jewel_code_certificate",
            },
        ),
        migrations.CreateModel(
            name="RateCard",
            fields=[
                ("rate_card_id", models.AutoField(primary_key=True, serialize=False)),
                ("code", models.CharField(max_length=32, unique=True)),
                (
                    "card_type",
                    models.CharField(
                        choices=[("COST", "Cost"), ("SALE", "Sale")], max_length=8
                    ),
                ),
                ("effective_from", models.DateField()),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="created_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "rate_card",
            },
        ),
        migrations.CreateModel(
            name="RateCardLine",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("size_band", models.CharField(blank=True, default="", max_length=64)),
                ("rate", models.DecimalField(decimal_places=4, max_digits=14)),
                (
                    "rate_uom",
                    models.CharField(
                        choices=[
                            ("CT", "Carat"),
                            ("GM", "Gram"),
                            ("RATTI", "Ratti"),
                            ("PCS", "Pieces"),
                        ],
                        max_length=8,
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        db_column="material_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="card_lines",
                        to="stock.material",
                    ),
                ),
                (
                    "rate_card",
                    models.ForeignKey(
                        db_column="rate_card_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="stock.ratecard",
                    ),
                ),
            ],
            options={
                "db_table": "rate_card_line",
            },
        ),
        migrations.CreateModel(
            name="RateChart",
            fields=[
                ("chart_id", models.AutoField(primary_key=True, serialize=False)),
                ("code", models.CharField(max_length=32)),
                ("name", models.CharField(max_length=80)),
                ("version_no", models.IntegerField(default=1)),
                ("is_default", models.BooleanField(default=False)),
                ("is_locked", models.BooleanField(default=False)),
                ("note", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="created_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "forked_from",
                    models.ForeignKey(
                        blank=True,
                        db_column="forked_from",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="forks",
                        to="stock.ratechart",
                    ),
                ),
            ],
            options={
                "db_table": "rate_chart",
                "ordering": ["-is_default", "code", "-version_no"],
            },
        ),
        migrations.CreateModel(
            name="RateChartLine",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("size_band", models.CharField(blank=True, default="", max_length=64)),
                (
                    "cost_rate",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                (
                    "sale_rate",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                ("rate_uom", models.CharField(blank=True, max_length=8, null=True)),
                (
                    "chart",
                    models.ForeignKey(
                        db_column="chart_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="stock.ratechart",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        db_column="material_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="chart_lines",
                        to="stock.material",
                    ),
                ),
            ],
            options={
                "db_table": "rate_chart_line",
            },
        ),
        migrations.CreateModel(
            name="RepairJob",
            fields=[
                (
                    "repair_job_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("job_no", models.CharField(max_length=40, unique=True)),
                ("from_bom_version", models.IntegerField()),
                ("to_bom_version", models.IntegerField(blank=True, null=True)),
                ("opened_on", models.DateField()),
                ("closed_on", models.DateField(blank=True, null=True)),
                ("fault_description", models.TextField()),
                ("work_done", models.TextField(blank=True, null=True)),
                (
                    "labour_cost",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("WITH_VENDOR", "With vendor"),
                            ("DONE", "Done"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="OPEN",
                        max_length=16,
                    ),
                ),
                (
                    "closed_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="closed_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "opened_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="opened_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "piece",
                    models.ForeignKey(
                        db_column="jewel_code_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="repairs",
                        to="stock.piece",
                    ),
                ),
                (
                    "return_location",
                    models.ForeignKey(
                        blank=True,
                        db_column="return_location_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="stock.location",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        blank=True,
                        db_column="vendor_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="repairs",
                        to="stock.vendor",
                    ),
                ),
            ],
            options={
                "db_table": "repair_job",
                "ordering": ["-opened_on"],
            },
        ),
        migrations.CreateModel(
            name="BomVersion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version_no", models.IntegerField()),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("INITIAL", "Initial"),
                            ("REPAIR", "Repair"),
                            ("CORRECTION", "Correction"),
                            ("RECOST", "Recost"),
                        ],
                        default="INITIAL",
                        max_length=16,
                    ),
                ),
                ("note", models.TextField(blank=True, null=True)),
                (
                    "net_metal_wt_gm",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                (
                    "bom_weight_gm",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                (
                    "total_cost_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "total_sale_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "making_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "goods_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("is_current", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="created_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "piece",
                    models.ForeignKey(
                        db_column="jewel_code_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bom_versions",
                        to="stock.piece",
                    ),
                ),
                (
                    "cost_rate_card",
                    models.ForeignKey(
                        blank=True,
                        db_column="cost_rate_card_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="stock.ratecard",
                    ),
                ),
                (
                    "sale_rate_card",
                    models.ForeignKey(
                        blank=True,
                        db_column="sale_rate_card_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="stock.ratecard",
                    ),
                ),
                (
                    "repair_job",
                    models.ForeignKey(
                        blank=True,
                        db_column="repair_job_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bom_versions",
                        to="stock.repairjob",
                    ),
                ),
            ],
            options={
                "db_table": "bom_version",
                "ordering": ["piece_id", "version_no"],
            },
        ),
        migrations.CreateModel(
            name="RepairMaterialChange",
            fields=[
                ("change_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "action",
                    models.CharField(
                        choices=[("REMOVE", "Remove"), ("ADD", "Add")], max_length=8
                    ),
                ),
                ("size_band", models.CharField(blank=True, default="", max_length=64)),
                ("pcs", models.IntegerField(blank=True, null=True)),
                (
                    "qty_value",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "qty_uom",
                    models.CharField(
                        choices=[
                            ("CT", "Carat"),
                            ("GM", "Gram"),
                            ("RATTI", "Ratti"),
                            ("PCS", "Pieces"),
                        ],
                        max_length=8,
                    ),
                ),
                (
                    "cost_rate",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                (
                    "sale_rate",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                ("returned_to_stock", models.BooleanField(default=True)),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "material",
                    models.ForeignKey(
                        db_column="material_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="stock.material",
                    ),
                ),
                (
                    "repair_job",
                    models.ForeignKey(
                        db_column="repair_job_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="changes",
                        to="stock.repairjob",
                    ),
                ),
            ],
            options={
                "db_table": "repair_material_change",
            },
        ),
        migrations.CreateModel(
            name="Sale",
            fields=[
                ("sale_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("bom_version_at_sale", models.IntegerField(blank=True, null=True)),
                ("sold_on", models.DateField()),
                (
                    "customer_name",
                    models.CharField(blank=True, max_length=160, null=True),
                ),
                (
                    "customer_phone",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                ("sold_price", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "discount_amt",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "cost_at_sale",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "margin_amt",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.db.models.expressions.CombinedExpression(
                            django.db.models.expressions.CombinedExpression(
                                models.F("sold_price"), "-", models.F("discount_amt")
                            ),
                            "-",
                            models.F("cost_at_sale"),
                        ),
                        output_field=models.DecimalField(
                            decimal_places=2, max_digits=14
                        ),
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("STOCK", "Stock"), ("CRM", "CRM")],
                        default="STOCK",
                        max_length=8,
                    ),
                ),
                (
                    "product_category",
                    models.CharField(
                        blank=True,
                        help_text="cat1/cat2/cat3 — the FoN commission category.",
                        max_length=8,
                        null=True,
                    ),
                ),
                ("invoice_no", models.CharField(blank=True, max_length=80, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "legacy_id",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sales",
                        to="crm.customer",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        db_column="location_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales",
                        to="stock.location",
                    ),
                ),
                (
                    "piece",
                    models.ForeignKey(
                        blank=True,
                        db_column="jewel_code_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales",
                        to="stock.piece",
                    ),
                ),
                (
                    "salesperson",
                    models.ForeignKey(
                        blank=True,
                        db_column="salesperson_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "sale",
                "ordering": ["-sold_on", "-sale_id"],
            },
        ),
        migrations.CreateModel(
            name="Scenario",
            fields=[
                ("scenario_id", models.AutoField(primary_key=True, serialize=False)),
                ("code", models.CharField(max_length=32, unique=True)),
                ("name", models.CharField(max_length=80)),
                (
                    "method",
                    models.CharField(
                        choices=[("CHART", "Chart"), ("VALUE_ADDED", "Value added")],
                        max_length=16,
                    ),
                ),
                (
                    "target_pct",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=8, null=True
                    ),
                ),
                (
                    "spread_over",
                    models.JSONField(
                        default=list,
                        help_text='Material categories the markup lands on, e.g. ["DIAMOND","POLKI"].',
                    ),
                ),
                (
                    "spread_by",
                    models.CharField(
                        choices=[("COST", "Cost"), ("WEIGHT", "Weight")],
                        default="COST",
                        max_length=8,
                    ),
                ),
                (
                    "min_multiple",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("1.0"), max_digits=8
                    ),
                ),
                (
                    "max_multiple",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("8.0"), max_digits=8
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("note", models.TextField(blank=True, null=True)),
                (
                    "chart",
                    models.ForeignKey(
                        blank=True,
                        db_column="chart_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scenarios",
                        to="stock.ratechart",
                    ),
                ),
            ],
            options={
                "db_table": "scenario",
            },
        ),
        migrations.AddField(
            model_name="piece",
            name="scenario",
            field=models.ForeignKey(
                blank=True,
                db_column="scenario_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pieces",
                to="stock.scenario",
            ),
        ),
        migrations.CreateModel(
            name="ScenarioRole",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("may_see", models.BooleanField(default=True)),
                ("may_switch", models.BooleanField(default=False)),
                (
                    "group",
                    models.ForeignKey(
                        db_column="role_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scenario_roles",
                        to="auth.group",
                    ),
                ),
                (
                    "scenario",
                    models.ForeignKey(
                        db_column="scenario_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roles",
                        to="stock.scenario",
                    ),
                ),
            ],
            options={
                "db_table": "scenario_role",
            },
        ),
        migrations.CreateModel(
            name="StockCount",
            fields=[
                ("count_id", models.AutoField(primary_key=True, serialize=False)),
                ("count_ref", models.CharField(max_length=64, unique=True)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("CLOSED", "Closed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="OPEN",
                        max_length=16,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "result",
                    models.JSONField(
                        blank=True,
                        help_text="Frozen at close. A closed count is never recomputed.",
                        null=True,
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="approved_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "counted_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="counted_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        db_column="location_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="counts",
                        to="stock.location",
                    ),
                ),
            ],
            options={
                "db_table": "stock_count",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="StockCountScan",
            fields=[
                ("scan_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("scanned_at", models.DateTimeField(auto_now_add=True)),
                ("verdict", models.CharField(blank=True, max_length=16, null=True)),
                (
                    "count",
                    models.ForeignKey(
                        db_column="count_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scans",
                        to="stock.stockcount",
                    ),
                ),
                (
                    "piece",
                    models.ForeignKey(
                        db_column="jewel_code_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="count_scans",
                        to="stock.piece",
                    ),
                ),
                (
                    "scanned_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="scanned_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "stock_count_scan",
            },
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                ("movement_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "move_type",
                    models.CharField(
                        choices=[
                            ("RECEIPT", "Receipt"),
                            ("TRANSFER_OUT", "Transfer out"),
                            ("TRANSFER_IN", "Transfer in"),
                            ("RESERVE", "Reserve"),
                            ("UNRESERVE", "Unreserve"),
                            ("APPROVAL_OUT", "Approval out"),
                            ("APPROVAL_RETURN", "Approval return"),
                            ("REPAIR_OUT", "Repair out"),
                            ("REPAIR_IN", "Repair in"),
                            ("SALE", "Sale"),
                            ("SALE_RETURN", "Sale return"),
                            ("MELT", "Melt"),
                            ("LOST", "Lost"),
                            ("COUNT_ADJUSTMENT", "Count adjustment"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "resulting_state",
                    models.CharField(
                        choices=[
                            ("NOT_RECEIVED", "Not received"),
                            ("IN_STOCK", "In stock"),
                            ("RESERVED", "Reserved"),
                            ("ON_APPROVAL", "On approval"),
                            ("IN_TRANSIT", "In transit"),
                            ("IN_REPAIR", "In repair"),
                            ("SOLD", "Sold"),
                            ("MELTED", "Melted"),
                            ("LOST", "Lost"),
                        ],
                        max_length=16,
                    ),
                ),
                ("moved_at", models.DateTimeField()),
                (
                    "reference_no",
                    models.CharField(blank=True, max_length=80, null=True),
                ),
                ("party_name", models.CharField(blank=True, max_length=160, null=True)),
                ("reason", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "from_location",
                    models.ForeignKey(
                        blank=True,
                        db_column="from_location_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movements_out",
                        to="stock.location",
                    ),
                ),
                (
                    "piece",
                    models.ForeignKey(
                        db_column="jewel_code_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movements",
                        to="stock.piece",
                    ),
                ),
                (
                    "to_location",
                    models.ForeignKey(
                        blank=True,
                        db_column="to_location_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movements_in",
                        to="stock.location",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_column="user_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "stock_movement",
                "ordering": ["-moved_at", "-movement_id"],
            },
        ),
        migrations.CreateModel(
            name="Style",
            fields=[
                ("style_id", models.AutoField(primary_key=True, serialize=False)),
                ("style_code", models.CharField(max_length=64, unique=True)),
                ("name", models.CharField(blank=True, max_length=160, null=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("SKETCH", "Sketch"),
                            ("DESIGN_INSPIRATION", "Design inspiration"),
                            ("RENDERING", "Rendering"),
                            ("CAD", "CAD"),
                            ("IN_STOCK_DESIGN", "In stock"),
                            ("OUT_OF_STOCK_DESIGN", "Out of stock"),
                            ("DISCONTINUED", "Discontinued"),
                        ],
                        default="SKETCH",
                        max_length=24,
                    ),
                ),
                ("story", models.TextField(blank=True, null=True)),
                ("website_description", models.TextField(blank=True, null=True)),
                ("designed_on", models.DateField(blank=True, null=True)),
                (
                    "version_label",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                ("nos_min_qty", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        db_column="category_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="styles",
                        to="stock.category",
                    ),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        blank=True,
                        db_column="collection_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="styles",
                        to="stock.collection",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="created_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "designer_user",
                    models.ForeignKey(
                        blank=True,
                        db_column="designer_user_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="designed_styles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent_style",
                    models.ForeignKey(
                        blank=True,
                        db_column="parent_style_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="versions",
                        to="stock.style",
                    ),
                ),
            ],
            options={
                "db_table": "style",
                "ordering": ["style_code"],
            },
        ),
        migrations.AddField(
            model_name="piece",
            name="style",
            field=models.ForeignKey(
                db_column="style_id",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pieces",
                to="stock.style",
            ),
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("tag_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=80)),
                ("tag_group", models.CharField(max_length=40)),
            ],
            options={
                "db_table": "tag",
                "unique_together": {("tag_group", "name")},
            },
        ),
        migrations.CreateModel(
            name="StyleTag",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "style",
                    models.ForeignKey(
                        db_column="style_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stock.style",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        db_column="tag_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stock.tag",
                    ),
                ),
            ],
            options={
                "db_table": "style_tag",
            },
        ),
        migrations.AddField(
            model_name="style",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="styles",
                through="stock.StyleTag",
                to="stock.tag",
            ),
        ),
        migrations.AddField(
            model_name="piece",
            name="vendor",
            field=models.ForeignKey(
                blank=True,
                db_column="vendor_id",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pieces",
                to="stock.vendor",
            ),
        ),
        migrations.CreateModel(
            name="JobCard",
            fields=[
                ("job_card_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("job_no", models.CharField(max_length=40, unique=True)),
                ("issued_on", models.DateField()),
                ("expected_on", models.DateField(blank=True, null=True)),
                ("received_on", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("WITH_VENDOR", "With vendor"),
                            ("RECEIVED", "Received"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="OPEN",
                        max_length=16,
                    ),
                ),
                (
                    "estimated_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "actual_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "digital_copy_url",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="created_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "piece",
                    models.ForeignKey(
                        blank=True,
                        db_column="jewel_code_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="job_cards",
                        to="stock.piece",
                    ),
                ),
                (
                    "style",
                    models.ForeignKey(
                        db_column="style_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="job_cards",
                        to="stock.style",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        blank=True,
                        db_column="vendor_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="job_cards",
                        to="stock.vendor",
                    ),
                ),
            ],
            options={
                "db_table": "job_card",
            },
        ),
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                ("log_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("table_name", models.CharField(max_length=64)),
                ("record_pk", models.CharField(max_length=120)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("INSERT", "Insert"),
                            ("UPDATE", "Update"),
                            ("DELETE", "Delete"),
                            ("VIEW_COST", "View_Cost"),
                            ("EXPORT", "Export"),
                            ("LOGIN", "Login"),
                            ("MELT", "Melt"),
                            ("REPAIR", "Repair"),
                            ("IMPORT", "Import"),
                            ("SALE", "Sale"),
                            ("REVERSAL", "Reversal"),
                        ],
                        max_length=16,
                    ),
                ),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                ("old_values", models.JSONField(blank=True, null=True)),
                ("new_values", models.JSONField(blank=True, null=True)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("export_id", models.CharField(blank=True, max_length=64, null=True)),
                ("row_count", models.IntegerField(blank=True, null=True)),
                ("detail", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_column="user_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "activity_log",
                "ordering": ["-changed_at"],
                "indexes": [
                    models.Index(
                        fields=["table_name", "record_pk", "-changed_at"],
                        name="idx_log_rec",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MaterialInventory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("size_band", models.CharField(blank=True, default="", max_length=64)),
                (
                    "qty_value",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "qty_uom",
                    models.CharField(
                        choices=[
                            ("CT", "Carat"),
                            ("GM", "Gram"),
                            ("RATTI", "Ratti"),
                            ("PCS", "Pieces"),
                        ],
                        max_length=8,
                    ),
                ),
                ("pcs", models.IntegerField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "location",
                    models.ForeignKey(
                        db_column="location_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventory",
                        to="stock.location",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        db_column="material_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventory",
                        to="stock.material",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "material inventory",
                "db_table": "material_inventory",
                "unique_together": {("material", "location", "size_band")},
            },
        ),
        migrations.AddConstraint(
            model_name="material",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("mat_class", "METAL"), _negated=True),
                    ("metal__isnull", False),
                    _connector="OR",
                ),
                name="material_metal_required",
            ),
        ),
        migrations.AddConstraint(
            model_name="metalpurity",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("sale_factor__gt", 0),
                    ("true_fineness__gt", 0),
                    ("true_fineness__lte", 1),
                ),
                name="metal_purity_factors_sane",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="catalogueitem",
            unique_together={("catalogue", "piece")},
        ),
        migrations.AddIndex(
            model_name="bomline",
            index=models.Index(fields=["piece", "version_no"], name="idx_jml"),
        ),
        migrations.AlterUniqueTogether(
            name="bomline",
            unique_together={("piece", "version_no", "line_no")},
        ),
        migrations.AlterUniqueTogether(
            name="piececertificate",
            unique_together={("company", "cert_number")},
        ),
        migrations.AlterUniqueTogether(
            name="ratecardline",
            unique_together={("rate_card", "material", "size_band")},
        ),
        migrations.AddConstraint(
            model_name="ratechart",
            constraint=models.UniqueConstraint(
                fields=("code", "version_no"), name="rate_chart_code_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="ratechart",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("is_default",),
                name="rate_chart_one_default",
            ),
        ),
        migrations.AddConstraint(
            model_name="ratechartline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("cost_rate__isnull", True), ("cost_rate__gte", 0), _connector="OR"
                ),
                name="chart_cost_nonneg",
            ),
        ),
        migrations.AddConstraint(
            model_name="ratechartline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("sale_rate__isnull", True), ("sale_rate__gte", 0), _connector="OR"
                ),
                name="chart_sale_nonneg",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="ratechartline",
            unique_together={("chart", "material", "size_band")},
        ),
        migrations.AddConstraint(
            model_name="bomversion",
            constraint=models.UniqueConstraint(
                fields=("piece", "version_no"), name="bom_version_pk"
            ),
        ),
        migrations.AddConstraint(
            model_name="bomversion",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_current", True)),
                fields=("piece",),
                name="uq_current_bom",
            ),
        ),
        migrations.AddConstraint(
            model_name="sale",
            constraint=models.UniqueConstraint(
                condition=models.Q(("piece__isnull", False)),
                fields=("piece",),
                name="uq_sale_piece_once",
            ),
        ),
        migrations.AddConstraint(
            model_name="scenario",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("is_default",),
                name="scenario_one_default",
            ),
        ),
        migrations.AddConstraint(
            model_name="scenario",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("method", "VALUE_ADDED"), _negated=True),
                    ("target_pct__isnull", False),
                    _connector="OR",
                ),
                name="scenario_value_added_needs_target",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="scenariorole",
            unique_together={("scenario", "group")},
        ),
        migrations.AddConstraint(
            model_name="stockcount",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "OPEN")),
                fields=("location",),
                name="stock_count_one_open_per_location",
            ),
        ),
        migrations.AddIndex(
            model_name="stockcountscan",
            index=models.Index(
                fields=["count", "-scanned_at"], name="stock_count_scan_seen"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="stockcountscan",
            unique_together={("count", "piece")},
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(fields=["piece", "-moved_at"], name="idx_move_jc"),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(fields=["move_type", "-moved_at"], name="idx_move_type"),
        ),
        migrations.AlterUniqueTogether(
            name="styletag",
            unique_together={("style", "tag")},
        ),
        migrations.AddIndex(
            model_name="piece",
            index=models.Index(fields=["style"], name="idx_jewel_style"),
        ),
        migrations.AddIndex(
            model_name="piece",
            index=models.Index(
                fields=["stock_state", "location"], name="idx_jewel_state"
            ),
        ),
        migrations.AddConstraint(
            model_name="piece",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("stock_state__in", ["SOLD", "MELTED", "LOST", "NOT_RECEIVED"]),
                    ("location__isnull", False),
                    _connector="OR",
                ),
                name="live_piece_has_location",
            ),
        ),
        migrations.AddConstraint(
            model_name="piece",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("stock_state__in", ["SOLD", "MELTED", "LOST"]), _negated=True
                    ),
                    ("disposed_on__isnull", False),
                    _connector="OR",
                ),
                name="dead_piece_has_date",
            ),
        ),
    ]
