# Generated by Django 5.2.17 on 2026-08-27 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_material_class_becomes_the_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='multipliers',
            field=models.JSONField(blank=True, default=dict, help_text='Category multipliers, e.g. {"DIAMOND": "2.5"}. A category left out passes at 1×.'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='method',
            field=models.CharField(choices=[('CHART', 'Rate chart — take the sale rate as written'), ('VALUE_ADDED', 'Target margin — cost + %, absorbed by the chosen categories'), ('MULTIPLIER', 'Category multipliers — a factor per material category')], max_length=16),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='spread_by',
            field=models.CharField(choices=[('COST', 'Their cost'), ('WEIGHT', 'Their weight'), ('CHART', 'Their rate-chart sale value')], default='COST', max_length=8),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='spread_over',
            field=models.JSONField(blank=True, default=list, help_text='Material categories the markup lands on, e.g. ["DIAMOND","POLKI"]. Empty means every priceable non-metal category.'),
        ),
    ]
