# Generated by Django 5.2.17 on 2026-08-31 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_scenario_multipliers_alter_scenario_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='remarks',
            field=models.TextField(blank=True, help_text="The legacy purchase form's free-text remarks.", null=True),
        ),
    ]
