# Generated by Django 5.2.17 on 2026-09-01 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0004_location_outreachentry"),
        ("stock", "0006_sale_remarks"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="crm_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sales",
                to="crm.order",
            ),
        ),
    ]
