# Generated by Django 5.2.17 on 2026-09-01 18:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediahub', '0005_alter_mediaasset_kind'),
        ('stock', '0007_sale_carries_the_crm_order_it_was_billed_from'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('batch_id', models.AutoField(primary_key=True, serialize=False)),
                ('source', models.CharField(default='IVY', max_length=32)),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('REVIEWING', 'Reviewing'), ('COMMITTING', 'Committing'), ('IMAGES', 'Attaching images'), ('DONE', 'Done'), ('FAILED', 'Failed')], default='UPLOADED', max_length=16)),
                ('decisions', models.JSONField(blank=True, default=dict)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('images_done', models.IntegerField(default=0)),
                ('images_total', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('media', models.ForeignKey(db_column='media_id', on_delete=django.db.models.deletion.PROTECT, related_name='import_batches', to='mediahub.mediaasset')),
            ],
            options={
                'db_table': 'import_batch',
                'ordering': ['-created_at'],
            },
        ),
    ]
