# Generated by Django 5.2.17 on 2026-09-16 06:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_importbatch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='style',
            name='talking_points',
            field=models.TextField(blank=True, help_text='One per line. What to lead with when selling this design.', null=True),
        ),
        migrations.CreateModel(
            name='PieceLink',
            fields=[
                ('link_id', models.AutoField(primary_key=True, serialize=False)),
                ('kind', models.CharField(default='Matching set', max_length=48)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('other', models.ForeignKey(db_column='other_jewel_code_id', on_delete=django.db.models.deletion.CASCADE, related_name='links_in', to='stock.piece')),
                ('piece', models.ForeignKey(db_column='jewel_code_id', on_delete=django.db.models.deletion.CASCADE, related_name='links_out', to='stock.piece')),
            ],
            options={
                'db_table': 'piece_link',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('piece', 'other'), name='piece_link_is_unique'), models.CheckConstraint(condition=models.Q(('piece', models.F('other')), _negated=True), name='piece_link_needs_two_pieces')],
            },
        ),
    ]
