# Generated by Django 5.2.17 on 2026-09-30 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_style_talking_points_piecelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='terms',
            field=models.CharField(blank=True, help_text='Payment terms, e.g. 30 days, Advance.', max_length=60),
        ),
    ]
