# Generated by Django 5.2.17 on 2026-08-24 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("stock", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="home_location",
            field=models.ForeignKey(
                blank=True,
                help_text="Empty means every location is visible — the rule app.visible_locations() applied.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="home_users",
                to="stock.location",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="locations",
            field=models.ManyToManyField(
                blank=True,
                help_text="Extra locations this user may see.",
                related_name="users",
                to="stock.location",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
    ]
