# Generated by Django 5.2.17 on 2026-10-09 08:51

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models

#: what each role could open on the day screens moved into the database —
#: copied, not imported, so this migration means the same thing forever.
#: Every role could open the CRM before it was a screen, so every role keeps it.
SCREENS_THEN = {
    "ADMIN": ["dash", "stock", "count", "repairs", "melt", "styles", "reports", "data", "audit", "admin", "crm"],
    "ACCOUNTS": ["dash", "stock", "repairs", "count", "styles", "reports", "crm"],
    "SALES": ["dash", "stock", "count", "styles", "crm"],
    "GRAPHIC": ["styles", "crm"],
    "PRODUCTION": ["stock", "repairs", "styles", "crm"],
}
NAMES_THEN = {
    "ADMIN": "Admin / Owner",
    "ACCOUNTS": "Accounts",
    "SALES": "Sales / Showroom",
    "GRAPHIC": "Graphic / Media",
    "PRODUCTION": "Production",
}


def roles_from_groups(apps, schema_editor):
    """A role for every group, opening what that group's logins opened yesterday.

    A group outside the five fell back to Graphic's screens; it keeps those.
    """
    Group = apps.get_model("auth", "Group")
    Role = apps.get_model("accounts", "Role")
    for group in Group.objects.all():
        Role.objects.create(
            group=group,
            name=NAMES_THEN.get(group.name, group.name.title()),
            screens=SCREENS_THEN.get(group.name, SCREENS_THEN["GRAPHIC"]),
        )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_rm'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='role', serialize=False, to='auth.group')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('screens', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=16), blank=True, default=list, size=None)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RunPython(roles_from_groups, migrations.RunPython.noop),
    ]
