# Generated by Django 5.2.17 on 2026-09-28 15:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '0009_style_talking_points_piecelink'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoxColour',
            fields=[
                ('code', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=80)),
                ('swatch', models.CharField(help_text='A CSS background: a colour, a gradient or a hatch.', max_length=200)),
                ('confirmed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'inv_box_colour',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True)),
                ('family', models.CharField(max_length=2)),
                ('cls', models.CharField(max_length=2)),
                ('seq', models.CharField(max_length=8)),
                ('box_colour', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='inventory.boxcolour')),
            ],
            options={
                'verbose_name_plural': 'batches',
                'db_table': 'inv_batch',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CodePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('family', 'Material family'), ('class', 'Class')], max_length=8)),
                ('code', models.CharField(max_length=2)),
                ('label', models.CharField(max_length=80)),
                ('confirmed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'inv_code_part',
                'ordering': ['kind', 'code'],
                'constraints': [models.UniqueConstraint(fields=('kind', 'code'), name='inv_code_part_key')],
            },
        ),
        migrations.CreateModel(
            name='Pouch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(editable=False, max_length=12, unique=True)),
                ('pouch_no', models.CharField(blank=True, max_length=16, null=True)),
                ('carton', models.CharField(blank=True, max_length=32, verbose_name='box no.')),
                ('category', models.CharField(blank=True, max_length=80)),
                ('stone_name', models.CharField(blank=True, max_length=120)),
                ('colour', models.CharField(blank=True, max_length=80)),
                ('shape', models.CharField(blank=True, max_length=80)),
                ('cut', models.CharField(blank=True, max_length=80)),
                ('quality', models.CharField(blank=True, max_length=20)),
                ('size_text', models.CharField(blank=True, max_length=80)),
                ('countable', models.BooleanField(default=True, help_text='A blank Pcs in the register: too small or too many to count.')),
                ('remarks', models.TextField(blank=True)),
                ('src', models.CharField(blank=True, help_text='Sheet and row it came from, e.g. SP!104.', max_length=24)),
                ('treatment', models.CharField(blank=True, choices=[('Unknown', 'Unknown'), ('None (verified)', 'None (verified)'), ('Heated', 'Heated'), ('Oiled / Resin', 'Oiled / Resin'), ('Dyed', 'Dyed'), ('Bleached', 'Bleached'), ('Stabilised / Impregnated', 'Stabilised / Impregnated'), ('Coated (incl. AB / iridescent)', 'Coated (incl. AB / iridescent)'), ('Irradiated', 'Irradiated'), ('Diffused', 'Diffused'), ('Glass-filled', 'Glass-filled'), ('Reconstituted / Composite', 'Reconstituted / Composite'), ('Laser Drilled', 'Laser Drilled')], max_length=40)),
                ('origin', models.CharField(blank=True, choices=[('Iran (feroza)', 'Iran (feroza)'), ('China', 'China'), ('Burma / Myanmar', 'Burma / Myanmar'), ('Sri Lanka (Ceylon)', 'Sri Lanka (Ceylon)'), ('Zambia', 'Zambia'), ('Brazil', 'Brazil'), ('Tanzania (Merelani)', 'Tanzania (Merelani)'), ('Africa — other', 'Africa — other'), ('India', 'India')], max_length=40)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pouches', to='inventory.batch')),
                ('import_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='stock.importbatch')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='stock.vendor')),
            ],
            options={
                'verbose_name_plural': 'pouches',
                'db_table': 'inv_pouch',
                'ordering': ['batch__code', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reason', models.CharField(choices=[('Opening Balance', 'Opening Balance'), ('Purchase', 'Purchase'), ('Purchase Return', 'Purchase Return'), ('Sale', 'Sale'), ('Sales Return', 'Sales Return'), ('Memo Out', 'Memo Out'), ('Memo In', 'Memo In'), ('Job Work Out', 'Job Work Out'), ('Job Work In', 'Job Work In'), ('Consumed in Production', 'Consumed'), ('Wastage / Loss in Process', 'Wastage'), ('Breakage', 'Breakage'), ('Split', 'Split'), ('Merge', 'Merge'), ('Transfer', 'Transfer'), ('Sample', 'Sample'), ('Recount Adjustment', 'Recount Adjustment')], max_length=32)),
                ('direction', models.CharField(choices=[('in', 'In'), ('out', 'Out')], max_length=3)),
                ('pcs', models.PositiveIntegerField(blank=True, null=True)),
                ('ct', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('challan_no', models.CharField(blank=True, max_length=40)),
                ('ref', models.CharField(blank=True, max_length=40)),
                ('note', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('counterparty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='stock.vendor')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('pouch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.pouch')),
            ],
            options={
                'db_table': 'inv_movement',
                'ordering': ['-occurred_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='PriceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('valuation', 'Valuation'), ('purchase', 'Purchase'), ('list', 'List')], max_length=10)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=14)),
                ('effective_from', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('pouch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prices', to='inventory.pouch')),
                ('set_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'inv_price',
                'ordering': ['-effective_from', '-pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='pouch',
            constraint=models.UniqueConstraint(condition=models.Q(('pouch_no__isnull', False)), fields=('batch', 'pouch_no'), name='inv_pouch_key'),
        ),
    ]
