# Generated by Django 5.2.17 on 2026-09-30 08:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_seed_codes'),
        ('stock', '0010_vendor_terms'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiamondCode',
            fields=[
                ('item_code', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('confirmed', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'db_table': 'inv_dia_code',
                'ordering': ['item_code'],
            },
        ),
        migrations.CreateModel(
            name='DiamondRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_text', models.CharField(blank=True, max_length=40)),
                ('cost_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('sale_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('effective_from', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'inv_dia_rate',
                'ordering': ['code', 'size_text', '-effective_from', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='DiamondTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('category', 'Category'), ('shape', 'Shape'), ('colour', 'Colour grade'), ('clarity', 'Clarity grade'), ('band', 'Size band')], max_length=10)),
                ('value', models.CharField(max_length=60)),
                ('sort', models.IntegerField(default=1000)),
                ('expands_to', models.CharField(blank=True, help_text='Space-separated single grades this range stands for.', max_length=120)),
            ],
            options={
                'db_table': 'inv_dia_term',
                'ordering': ['kind', 'sort', 'value'],
            },
        ),
        migrations.AlterField(
            model_name='movement',
            name='pouch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.pouch'),
        ),
        migrations.CreateModel(
            name='DiamondLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(editable=False, max_length=12, unique=True)),
                ('batch_no', models.CharField(blank=True, max_length=40)),
                ('size_text', models.CharField(blank=True, max_length=40)),
                ('ct_lo', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('ct_hi', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('src', models.CharField(blank=True, help_text='Sheet and row it came from.', max_length=24)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='inventory.diamondcode')),
                ('import_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='stock.importbatch')),
            ],
            options={
                'db_table': 'inv_dia_line',
                'ordering': ['pk'],
            },
        ),
        migrations.AddField(
            model_name='movement',
            name='diamond',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.diamondline'),
        ),
        migrations.AddConstraint(
            model_name='movement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('diamond__isnull', True), ('pouch__isnull', False)), models.Q(('diamond__isnull', False), ('pouch__isnull', True)), _connector='OR'), name='inv_movement_one_owner'),
        ),
        migrations.AddField(
            model_name='diamondrate',
            name='code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rates', to='inventory.diamondcode'),
        ),
        migrations.AddField(
            model_name='diamondrate',
            name='set_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='diamondterm',
            constraint=models.UniqueConstraint(fields=('kind', 'value'), name='inv_dia_term_key'),
        ),
        migrations.AddField(
            model_name='diamondline',
            name='band',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.diamondterm'),
        ),
        migrations.AddField(
            model_name='diamondline',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.diamondterm'),
        ),
        migrations.AddField(
            model_name='diamondline',
            name='shape_override',
            field=models.ForeignKey(blank=True, help_text='From a carat-band size prefix, when the code names no shape.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.diamondterm'),
        ),
        migrations.AddField(
            model_name='diamondcode',
            name='clarity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.diamondterm'),
        ),
        migrations.AddField(
            model_name='diamondcode',
            name='colour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.diamondterm'),
        ),
        migrations.AddField(
            model_name='diamondcode',
            name='shape',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.diamondterm'),
        ),
    ]
