# Generated by Django 5.2.17 on 2026-10-01 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_clarity_si_i1'),
    ]

    operations = [
        migrations.AddField(
            model_name='diamondline',
            name='colour_override',
            field=models.ForeignKey(blank=True, help_text="The file's colour for this line, when it differs from its code's (fancy lots under one code).", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.diamondterm'),
        ),
    ]
