# Generated by Django 5.2.17 on 2026-10-01 09:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_location_outreachentry'),
        ('inventory', '0006_line_colour_override'),
        ('stock', '0010_vendor_terms'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='reverses',
            field=models.OneToOneField(blank=True, help_text='The movement this one cancels.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal', to='inventory.movement'),
        ),
        migrations.AddField(
            model_name='pouch',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='The pouch a split took this one from.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='inventory.pouch'),
        ),
        migrations.AlterField(
            model_name='movement',
            name='direction',
            field=models.CharField(choices=[('in', 'In'), ('out', 'Out'), ('settle', 'Settle')], max_length=6),
        ),
        migrations.CreateModel(
            name='StockDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('purchase', 'Purchase'), ('job_work', 'Job work'), ('memo', 'Memo'), ('split', 'Split'), ('transfer', 'Transfer'), ('single', 'Single')], max_length=10)),
                ('number', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('reversed', 'Reversed')], default='open', max_length=10)),
                ('occurred_on', models.DateField(default=django.utils.timezone.localdate)),
                ('expected_back', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('currency', models.CharField(blank=True, choices=[('INR', 'INR'), ('USD', 'USD')], max_length=3)),
                ('fx_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='rate to INR')),
                ('landed_extras', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('from_pouch_no', models.CharField(blank=True, max_length=16)),
                ('to_pouch_no', models.CharField(blank=True, max_length=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crm.customer')),
                ('from_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.batch')),
                ('reverses', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversals', to='inventory.stockdocument')),
                ('to_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.batch')),
                ('vendor', models.ForeignKey(blank=True, help_text='The supplier (purchase, purchase return) or the karigar (job work).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='stock.vendor')),
            ],
            options={
                'db_table': 'inv_document',
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.AddField(
            model_name='movement',
            name='document',
            field=models.ForeignKey(blank=True, help_text='Empty for opening balances and import recounts.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.stockdocument'),
        ),
        migrations.AddConstraint(
            model_name='stockdocument',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'reversed'), _negated=True), fields=('kind', 'number'), name='inv_document_number'),
        ),
    ]
