# Generated by Django 5.2.17 on 2026-10-01 17:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_stones_ledger'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='reason',
            field=models.CharField(choices=[('Opening Balance', 'Opening Balance'), ('Purchase', 'Purchase'), ('Purchase Return', 'Purchase Return'), ('Sale', 'Sale'), ('Sales Return', 'Sales Return'), ('Memo Out', 'Memo Out'), ('Memo In', 'Memo In'), ('Job Work Out', 'Job Work Out'), ('Job Work In', 'Job Work In'), ('Consumed in Production', 'Consumed'), ('Wastage / Loss in Process', 'Wastage'), ('Breakage', 'Breakage'), ('Split', 'Split'), ('Merge', 'Merge'), ('Transfer', 'Transfer'), ('Sample', 'Sample'), ('Recount Adjustment', 'Recount Adjustment'), ('Returned Unused', 'Returned Unused'), ('Assort Out', 'Assort Out'), ('Assort In', 'Assort In')], max_length=32),
        ),
        migrations.AlterField(
            model_name='stockdocument',
            name='kind',
            field=models.CharField(choices=[('purchase', 'Purchase'), ('job_work', 'Job work'), ('memo', 'Memo'), ('split', 'Split'), ('transfer', 'Transfer'), ('single', 'Single'), ('dia_job', 'Job card'), ('dia_assort', 'Assortment'), ('dia_purchase', 'Diamond purchase')], max_length=12),
        ),
        migrations.CreateModel(
            name='DiamondLineCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_rate', models.DecimalField(decimal_places=4, max_digits=14)),
                ('effective_from', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('document', models.ForeignKey(blank=True, help_text='The purchase or assortment that set it; empty for a manual change.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.stockdocument')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='costs', to='inventory.diamondline')),
                ('set_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'inv_dia_line_cost',
                'ordering': ['-effective_from', '-pk'],
            },
        ),
    ]
