# Generated by Django 5.2.17 on 2026-10-04 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_diamond_ledgers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdocument',
            name='kind',
            field=models.CharField(choices=[('purchase', 'Purchase'), ('job_work', 'Job work'), ('memo', 'Memo'), ('split', 'Split'), ('transfer', 'Transfer'), ('merge', 'Merge'), ('single', 'Single'), ('dia_job', 'Job card'), ('dia_assort', 'Assortment'), ('dia_purchase', 'Diamond purchase')], max_length=12),
        ),
    ]
