# Generated by Django 5.2.17 on 2026-10-04 08:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_merge_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdocument',
            name='kind',
            field=models.CharField(choices=[('purchase', 'Purchase'), ('job_work', 'Job work'), ('memo', 'Memo'), ('split', 'Split'), ('transfer', 'Transfer'), ('merge', 'Merge'), ('stock_take', 'Stock take'), ('single', 'Single'), ('dia_job', 'Job card'), ('dia_assort', 'Assortment'), ('dia_purchase', 'Diamond purchase'), ('dia_count', 'Diamond stock take')], max_length=12),
        ),
        migrations.CreateModel(
            name='StockTake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=12, unique=True)),
                ('side', models.CharField(choices=[('stones', 'Stones'), ('diamonds', 'Diamonds')], max_length=8)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='open', max_length=10)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('result', models.JSONField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.batch')),
                ('box_colour', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.boxcolour')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.diamondterm')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('document', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_take', to='inventory.stockdocument')),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'inv_stock_take',
                'ordering': ['-started_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='StockTakeCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counted_pcs', models.PositiveIntegerField(blank=True, null=True)),
                ('counted_ct', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('book_pcs', models.PositiveIntegerField(blank=True, null=True)),
                ('book_ct', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('counted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('counted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('diamond', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.diamondline')),
                ('pouch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.pouch')),
                ('stock_take', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counts', to='inventory.stocktake')),
            ],
            options={
                'db_table': 'inv_stock_take_count',
                'constraints': [models.UniqueConstraint(condition=models.Q(('pouch__isnull', False)), fields=('stock_take', 'pouch'), name='inv_stock_take_count_pouch'), models.UniqueConstraint(condition=models.Q(('diamond__isnull', False)), fields=('stock_take', 'diamond'), name='inv_stock_take_count_diamond'), models.CheckConstraint(condition=models.Q(('pouch__isnull', True), ('diamond__isnull', True), _connector='XOR'), name='inv_stock_take_count_one_owner')],
            },
        ),
    ]
