# Generated by Django 5.2.17 on 2026-10-04 10:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_stock_take'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lookbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('note', models.TextField(blank=True, help_text='Shown to the client under the title.')),
                ('token', models.CharField(editable=False, max_length=32, unique=True)),
                ('shared', models.BooleanField(default=True, help_text='Off: the link answers as if it never existed.')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'inv_lookbook',
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='LookbookStone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('lookbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stones', to='inventory.lookbook')),
                ('pouch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.pouch')),
            ],
            options={
                'db_table': 'inv_lookbook_stone',
                'ordering': ['position', 'pk'],
                'constraints': [models.UniqueConstraint(fields=('lookbook', 'pouch'), name='inv_lookbook_stone_once')],
            },
        ),
    ]
