# Generated by Django 5.2.17 on 2026-08-24 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CrmSetting",
            fields=[
                (
                    "key",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("value", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["key"],
            },
        ),
        migrations.CreateModel(
            name="EtlException",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("run_at", models.DateTimeField(auto_now_add=True)),
                ("entity", models.CharField(max_length=40)),
                ("legacy_id", models.CharField(max_length=64)),
                ("problem", models.CharField(max_length=200)),
                ("detail", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-run_at", "entity"],
            },
        ),
        migrations.CreateModel(
            name="Salesperson",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "legacy_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=64, null=True, unique=True
                    ),
                ),
                (
                    "extra",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Keys from the original JSONB blob that have no column of their own.",
                    ),
                ),
                ("customer_code", models.CharField(max_length=32, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("mobile", models.CharField(blank=True, max_length=40)),
                ("landline", models.CharField(blank=True, max_length=40)),
                (
                    "preferred_phone",
                    models.CharField(blank=True, default="mobile", max_length=16),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("address", models.TextField(blank=True)),
                ("location", models.CharField(blank=True, max_length=120)),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("anniversary_date", models.DateField(blank=True, null=True)),
                ("engagement_date", models.DateField(blank=True, null=True)),
                ("wedding_date", models.DateField(blank=True, null=True)),
                (
                    "reference_type",
                    models.CharField(blank=True, default="Walk-in", max_length=40),
                ),
                (
                    "customer_type",
                    models.CharField(blank=True, default="Regular", max_length=32),
                ),
                (
                    "temperature",
                    models.CharField(
                        blank=True,
                        choices=[("Hot", "Hot"), ("Warm", "Warm"), ("Cold", "Cold")],
                        default="Warm",
                        max_length=16,
                    ),
                ),
                ("metal_preference", models.JSONField(blank=True, default=list)),
                (
                    "salesperson_preference",
                    models.CharField(blank=True, max_length=120),
                ),
                ("payment_preference", models.CharField(blank=True, max_length=32)),
                ("personal_observation", models.TextField(blank=True)),
                ("client_personal_info", models.TextField(blank=True)),
                ("is_fon", models.BooleanField(default=False)),
                ("fon_level", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("outreach_done", models.BooleanField(default=False)),
                ("outreach_last_date", models.DateField(blank=True, null=True)),
                ("outreach_notes", models.TextField(blank=True)),
                (
                    "fon_parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fon_children",
                        to="crm.customer",
                    ),
                ),
                (
                    "referrer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="referred_customers",
                        to="crm.customer",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ClientMaterial",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "legacy_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=64, null=True, unique=True
                    ),
                ),
                (
                    "extra",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Keys from the original JSONB blob that have no column of their own.",
                    ),
                ),
                ("status", models.CharField(max_length=40)),
                ("salesperson", models.CharField(blank=True, max_length=120)),
                ("notes", models.TextField(blank=True)),
                ("cm_code", models.CharField(max_length=32, unique=True)),
                ("received_date", models.DateField(blank=True, null=True)),
                ("jewellery_description", models.TextField(blank=True)),
                ("metal_type", models.CharField(blank=True, max_length=60)),
                (
                    "weight_grams",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                ("issue", models.TextField(blank=True)),
                ("design_notes", models.TextField(blank=True)),
                (
                    "estimated_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        help_text="Nullable on purpose: an orphaned customer_id becomes an exceptions-report row, never a silent drop.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)ss",
                        to="crm.customer",
                    ),
                ),
            ],
            options={
                "ordering": ["-received_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Enquiry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "legacy_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=64, null=True, unique=True
                    ),
                ),
                (
                    "extra",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Keys from the original JSONB blob that have no column of their own.",
                    ),
                ),
                ("status", models.CharField(max_length=40)),
                ("salesperson", models.CharField(blank=True, max_length=120)),
                ("notes", models.TextField(blank=True)),
                ("enquiry_code", models.CharField(max_length=32, unique=True)),
                ("enquiry_date", models.DateField(blank=True, null=True)),
                ("item_of_interest", models.CharField(blank=True, max_length=255)),
                (
                    "estimated_budget",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("metal_type", models.CharField(blank=True, max_length=60)),
                ("stone_details", models.TextField(blank=True)),
                ("design_brief", models.TextField(blank=True)),
                ("client_feedback", models.TextField(blank=True)),
                ("salesperson_feedback", models.TextField(blank=True)),
                (
                    "temperature",
                    models.CharField(blank=True, default="Warm", max_length=16),
                ),
                ("follow_up_date", models.DateField(blank=True, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        help_text="Nullable on purpose: an orphaned customer_id becomes an exceptions-report row, never a silent drop.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)ss",
                        to="crm.customer",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "enquiries",
                "ordering": ["-enquiry_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Gift",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(blank=True, null=True)),
                ("occasion", models.CharField(blank=True, max_length=120)),
                ("description", models.TextField(blank=True)),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gifts",
                        to="crm.customer",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Occasion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("occasion_type", models.CharField(max_length=60)),
                ("date", models.DateField(blank=True, null=True)),
                ("note", models.CharField(blank=True, max_length=255)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="occasions",
                        to="crm.customer",
                    ),
                ),
            ],
            options={
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "legacy_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=64, null=True, unique=True
                    ),
                ),
                (
                    "extra",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Keys from the original JSONB blob that have no column of their own.",
                    ),
                ),
                ("status", models.CharField(max_length=40)),
                ("salesperson", models.CharField(blank=True, max_length=120)),
                ("notes", models.TextField(blank=True)),
                ("order_code", models.CharField(max_length=32, unique=True)),
                ("order_date", models.DateField(blank=True, null=True)),
                ("item_description", models.TextField(blank=True)),
                ("metal_type", models.CharField(blank=True, max_length=60)),
                ("metal_purity", models.CharField(blank=True, max_length=32)),
                ("stone_details", models.TextField(blank=True)),
                ("diamond_details", models.TextField(blank=True)),
                ("design_brief", models.TextField(blank=True)),
                ("vendor", models.CharField(blank=True, max_length=120)),
                (
                    "weight_grams",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "advance_paid",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("billing_date", models.DateField(blank=True, null=True)),
                (
                    "billing_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("expected_delivery", models.DateField(blank=True, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        help_text="Nullable on purpose: an orphaned customer_id becomes an exceptions-report row, never a silent drop.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)ss",
                        to="crm.customer",
                    ),
                ),
                (
                    "enquiry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to="crm.enquiry",
                    ),
                ),
            ],
            options={
                "ordering": ["-order_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="RelatedPerson",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("relation", models.CharField(blank=True, max_length=60)),
                ("phone", models.CharField(blank=True, max_length=40)),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("note", models.CharField(blank=True, max_length=255)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related_people",
                        to="crm.customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Repair",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "legacy_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=64, null=True, unique=True
                    ),
                ),
                (
                    "extra",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Keys from the original JSONB blob that have no column of their own.",
                    ),
                ),
                ("status", models.CharField(max_length=40)),
                ("salesperson", models.CharField(blank=True, max_length=120)),
                ("notes", models.TextField(blank=True)),
                ("repair_code", models.CharField(max_length=32, unique=True)),
                ("received_date", models.DateField(blank=True, null=True)),
                ("jewellery_received", models.TextField(blank=True)),
                ("item_description", models.TextField(blank=True)),
                ("issue", models.TextField(blank=True)),
                ("karigar", models.CharField(blank=True, max_length=120)),
                (
                    "estimated_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "final_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("expected_return", models.DateField(blank=True, null=True)),
                ("actual_return", models.DateField(blank=True, null=True)),
                ("customer_approved", models.BooleanField(default=False)),
                ("customer_approval_date", models.DateField(blank=True, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        help_text="Nullable on purpose: an orphaned customer_id becomes an exceptions-report row, never a silent drop.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)ss",
                        to="crm.customer",
                    ),
                ),
            ],
            options={
                "ordering": ["-received_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="StatusEvent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entity_type", models.CharField(max_length=24)),
                ("entity_id", models.IntegerField()),
                ("date", models.DateField(blank=True, null=True)),
                ("status", models.CharField(max_length=60)),
                ("note", models.TextField(blank=True)),
                ("by", models.CharField(blank=True, max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["date", "id"],
                "indexes": [
                    models.Index(
                        fields=["entity_type", "entity_id"],
                        name="crm_statuse_entity__2ddd30_idx",
                    )
                ],
            },
        ),
    ]
