# Generated by Django 5.2.17 on 2026-08-26 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_clientmaterial_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientmaterial',
            name='cm_code',
            field=models.CharField(db_index=True, max_length=32),
        ),
    ]
