# Generated by Django 5.2.17 on 2026-08-26 11:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_alter_clientmaterial_cm_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OutreachEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('type', models.CharField(choices=[('phone', '📞 Phone Call'), ('whatsapp', '💬 WhatsApp'), ('pics', '📸 Pics Sent'), ('instore', '🏪 In-Store'), ('email', '✉️ Email')], default='phone', max_length=16)),
                ('outcome', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('next_follow_up', models.DateField(blank=True, null=True)),
                ('by', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outreach_log', to='crm.customer')),
            ],
            options={
                'verbose_name_plural': 'outreach entries',
                'ordering': ['-date', '-id'],
            },
        ),
    ]
