# Generated by Django 5.2.17 on 2026-08-24 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MediaAsset",
            fields=[
                ("media_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "media_ref",
                    models.CharField(blank=True, max_length=32, null=True, unique=True),
                ),
                ("scope", models.CharField(blank=True, max_length=32, null=True)),
                ("scope_id", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("PHOTO", "Photo"),
                            ("VIDEO", "Video"),
                            ("CAD", "CAD"),
                            ("PENCIL_DRAWING", "Pencil drawing"),
                            ("RENDER", "Render"),
                            ("CERTIFICATE_SCAN", "Certificate scan"),
                            ("JOB_CARD_SCAN", "Job card scan"),
                            ("GRAPH", "Graph"),
                        ],
                        default="PHOTO",
                        max_length=24,
                    ),
                ),
                (
                    "storage_provider",
                    models.CharField(default="CONTABO", max_length=16),
                ),
                (
                    "storage_key",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "storage_url",
                    models.URLField(blank=True, max_length=1000, null=True),
                ),
                ("thumb_url", models.URLField(blank=True, max_length=1000, null=True)),
                ("file_name", models.CharField(blank=True, max_length=255, null=True)),
                ("mime_type", models.CharField(blank=True, max_length=120, null=True)),
                ("sha256", models.CharField(blank=True, max_length=64, null=True)),
                ("bytes", models.BigIntegerField(blank=True, null=True)),
                ("caption", models.TextField(blank=True, null=True)),
                ("view_angle", models.CharField(blank=True, max_length=40, null=True)),
                ("rank_order", models.IntegerField(default=100)),
                ("is_catalogue_default", models.BooleanField(default=False)),
                ("is_archived", models.BooleanField(default=False)),
                ("width_px", models.IntegerField(blank=True, null=True)),
                ("height_px", models.IntegerField(blank=True, null=True)),
                ("file_size_kb", models.IntegerField(blank=True, null=True)),
                (
                    "derivative_kind",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "confirmed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Set when the object is known to exist in the bucket. An unconfirmed row is a reservation.",
                        null=True,
                    ),
                ),
                (
                    "derivative_of",
                    models.ForeignKey(
                        blank=True,
                        db_column="derivative_of",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="derivatives",
                        to="mediahub.mediaasset",
                    ),
                ),
            ],
            options={
                "db_table": "media_asset",
                "ordering": ["rank_order", "media_id"],
            },
        ),
    ]
