# Generated by Django 5.2.17 on 2026-08-24 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("mediahub", "0001_initial"),
        ("stock", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="mediaasset",
            name="piece",
            field=models.ForeignKey(
                blank=True,
                db_column="jewel_code_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="media",
                to="stock.piece",
            ),
        ),
        migrations.AddField(
            model_name="mediaasset",
            name="style",
            field=models.ForeignKey(
                blank=True,
                db_column="style_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="media",
                to="stock.style",
            ),
        ),
        migrations.AddField(
            model_name="mediaasset",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                db_column="uploaded_by",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="mediaasset",
            index=models.Index(fields=["piece", "rank_order"], name="idx_media_jc"),
        ),
        migrations.AddIndex(
            model_name="mediaasset",
            index=models.Index(fields=["style", "rank_order"], name="idx_media_st"),
        ),
        migrations.AddIndex(
            model_name="mediaasset",
            index=models.Index(fields=["scope", "scope_id"], name="idx_media_scope"),
        ),
        migrations.AddConstraint(
            model_name="mediaasset",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("style__isnull", False),
                    ("piece__isnull", False),
                    ("scope__isnull", False),
                    _connector="OR",
                ),
                name="media_asset_has_an_owner",
            ),
        ),
    ]
