# Generated by Django 5.2.17 on 2026-08-24 16:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mediahub", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mediaasset",
            name="uploaded_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
