# Generated by Django 5.2.17 on 2026-08-26 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediahub', '0003_alter_mediaasset_uploaded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaasset',
            name='inline_data',
            field=models.BinaryField(blank=True, help_text='Bytes held in the row because the object is not in the bucket yet.', null=True),
        ),
    ]
