# Generated by Django 5.2.17 on 2026-09-16 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediahub', '0005_alter_mediaasset_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaasset',
            name='kind',
            field=models.CharField(choices=[('PHOTO', 'Photo'), ('VIDEO', 'Video'), ('CAD', 'CAD'), ('PENCIL_DRAWING', 'Pencil drawing'), ('RENDER', 'Render'), ('CERTIFICATE_SCAN', 'Certificate scan'), ('JOB_CARD_SCAN', 'Job card scan'), ('GRAPH', 'Graph'), ('DOCUMENT', 'Document'), ('SELL_VIDEO', 'Sell video')], default='PHOTO', max_length=24),
        ),
    ]
