# Generated by Django 5.2.17 on 2026-09-28 12:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediahub', '0006_alter_mediaasset_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaasset',
            name='embedding',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, editable=False, null=True, size=None),
        ),
    ]
