# Generated by Django 5.2.17 on 2026-10-09 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediahub', '0008_piece_photos_onto_their_piece'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaasset',
            name='thumb_key',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
